[package]
name = "websocket"
version = "0.22.3"
authors = ["cyderize <admin@cyderize.org>", "Michael Eden <themichaeleden@gmail.com>"]

description = "A WebSocket (RFC6455) library for Rust."

documentation = "https://docs.rs/websocket/"
repository = "https://github.com/websockets-rs/rust-websocket"

readme = "README.md"

keywords = ["websocket", "websockets", "rfc6455", "async", "tokio"]
categories = ["asynchronous", "network-programming", "web-programming", "web-programming::websocket"]

license = "MIT"

[dependencies]
#hyper = "^0.10.6"
unicase = "1.0"
url = "1.0"
bitflags = "1.0.4"
rand = "0.6.1"
byteorder = "1.0"
sha1 = "0.6"
base64 = "0.10.0"
futures = { version = "0.1", optional = true }
tokio = { version = "0.1", optional = true }
tokio-tls = { version = "0.2.0", optional = true }
bytes = { version = "0.4", optional = true }
native-tls = { version = "0.2.1", optional = true }

httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
num_cpus = "1.0"
time = "0.1"
traitobject = "0.1"
typeable = "0.1"


[dev-dependencies]
futures-cpupool = "0.1"

[features]
default = ["sync", "sync-ssl", "async", "async-ssl"]
sync = []
sync-ssl = ["native-tls", "sync"]
async = ["tokio", "bytes", "futures"]
async-ssl = ["native-tls", "tokio-tls", "async"]
#nightly = ["hyper/nightly"]
